channels:
  - pytorch
  - conda-forge
dependencies:
  - python
  - matplotlib
  - numpy
  - scipy
  - pytorch
  - torchvision
  - imageio
  - tensorboardX
  - dpath
  - python-box
  - pyyaml
  - loguru
  - python-dotenv
  - scikit-image
  - GitPython
  - pyfiglet
  - pygments
  - psutil
  - termcolor
  - pip
  - pip:
    - pycontracts
    - configspace
    - duecredit
    - decopatch
    - getversion
    - dsntnn
    - highresnet
    - pywarm
    - termtables
